FROM node:20

WORKDIR /app

# Copy the entire project
COPY api ./api
COPY .env ./.env
COPY package.json ./package.json

# Install dependencies
RUN npm install

# Expose backend port
EXPOSE 5500

# Start command
CMD ["node", "api/server.js"]