FROM node:20

WORKDIR /app

# Copy the entire project
COPY back-end ./back-end
COPY .env ./.env
COPY package.json ./package.json

# Install dependencies
RUN npm install

# Expose backend port
EXPOSE 5500

# Start command
CMD ["node", "back-end/server.js"]