FROM node:20

WORKDIR /app

# Copy the entire project
COPY DataMiner ./DataMiner
COPY .env ./.env
COPY package.json ./package.json

# Install dependencies
RUN npm install

# Expose backend port
EXPOSE 600

# Start command
CMD ["node", "DataMiner/Scraper.js"]