<template>
  <div class="doc-content">
    <h1>Importing a Portfolio</h1>
    
    <section>
      <h2>Overview</h2>
      <p>
        The portfolio import feature allows you to restore previously exported portfolios or transfer 
        portfolio data from other sources. This is particularly useful for recovering backup data.
      </p>
    </section>

    <section>
      <h2>How to Import a Portfolio</h2>
      <ol>
        <li>Navigate to the <strong>Portfolio</strong> view from the main menu</li>
        <li>Locate the <strong>Import</strong> button in the header section</li>
        <li>Click the "Import" button to open the import dialog</li>
        <li>Click <strong>Choose File</strong> or drag and drop your CSV file into the upload area</li>
        <li>Select the CSV file you previously exported from Ereuna</li>
        <li>Review the import preview if available</li>
        <li>Click <strong>Import</strong> to begin the import process</li>
        <li>Wait for the confirmation message indicating successful import</li>
        <li>Review your imported portfolio to ensure all data loaded correctly</li>
      </ol>
    </section>
    <section>
      <h2>Important Considerations</h2>

       <div class="note-box">
        <h3>Critical: Format Must Match Export</h3>
        <p>
          The CSV file must be in the <strong>exact same format</strong> as the one generated by 
          Ereuna's export feature. The system expects specific column headers, data types, and 
          structure. Any modifications to the format may result in import failures or data corruption.
        </p>
      </div>
    </section>

    <section>
      <h2>Troubleshooting</h2>
      <div class="troubleshoot">
        <h3>Import fails with "Invalid format" error?</h3>
        <ul>
          <li>Verify the CSV was exported from Ereuna or matches the exact export format</li>
          <li>Check that no columns have been added, removed, or renamed</li>
          <li>Ensure the file is actually a CSV (not Excel .xlsx or other format)</li>
          <li>Open the file in a text editor to verify it uses commas as delimiters</li>
        </ul>

        <h3>Some transactions missing after import?</h3>
        <ul>
          <li>Review any warning messages that appeared during import</li>
          <li>Check that the original CSV file contains all expected transactions</li>
          <li>Verify that transaction dates are in the correct format</li>
          <li>Ensure no rows were accidentally deleted or modified in the CSV</li>
        </ul>

        <h3>Import process seems stuck?</h3>
        <ul>
          <li>Large portfolios may take several seconds to import - be patient</li>
          <li>Check your internet connection stability</li>
          <li>Don't close the browser window during import</li>
          <li>If stuck for more than a minute, refresh and try again</li>
        </ul>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
// Documentation component for Importing Portfolio feature
</script>

<style scoped>
.doc-content {
  max-width: 900px;
  color: var(--brand-text-primary);
  line-height: 1.8;
}

h1 {
  font-size: 2.5rem;
  font-weight: 700;
  color: var(--brand-text-primary);
  margin-bottom: 1.5rem;
  background: linear-gradient(135deg, var(--brand-gradient-start) 0%, var(--brand-gradient-end) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

h2 {
  font-size: 1.8rem;
  font-weight: 600;
  color: var(--brand-text-primary);
  margin-top: 2.5rem;
  margin-bottom: 1rem;
  padding-bottom: 0.5rem;
  border-bottom: 2px solid var(--brand-glass-border);
}

h3 {
  font-size: 1.3rem;
  font-weight: 600;
  color: var(--brand-text-primary);
  margin-top: 1.5rem;
  margin-bottom: 0.75rem;
}

section {
  margin-bottom: 2rem;
}

p {
  font-size: 1rem;
  color: var(--brand-text-secondary);
  margin-bottom: 1rem;
}

ol, ul {
  margin-left: 1.5rem;
  margin-bottom: 1rem;
}

li {
  font-size: 1rem;
  color: var(--brand-text-secondary);
  margin-bottom: 0.5rem;
  line-height: 1.6;
}

.demo-image {
  display: block;
  margin: 1.5rem auto;
  max-width: 100%;
  height: auto;
  border-radius: 12px;
  border: 1px solid var(--brand-glass-border);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.note-box {
  background: linear-gradient(135deg, rgba(122, 162, 247, 0.08) 0%, rgba(137, 221, 255, 0.08) 100%);
  border: 1px solid var(--brand-glass-border);
  border-radius: 12px;
  padding: 1.5rem;
  margin: 1.5rem 0;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.note-box h3 {
  margin-top: 0;
  color: var(--brand-gradient-start);
  font-size: 1.1rem;
}

.note-box p {
  margin-bottom: 0.5rem;
}

.note-box p:last-child {
  margin-bottom: 0;
}

.note-box ul {
  margin-bottom: 0.5rem;
  margin-top: 0.5rem;
}

.note-box ul:last-child {
  margin-bottom: 0;
}

.use-case {
  background: var(--brand-bg-secondary);
  border-radius: 12px;
  padding: 1.5rem;
  border: 1px solid var(--brand-glass-border);
}

.use-case h3 {
  color: var(--brand-gradient-start);
  margin-top: 1rem;
  font-size: 1.1rem;
}

.use-case h3:first-child {
  margin-top: 0;
}

.troubleshoot {
  background: var(--brand-bg-secondary);
  border-radius: 12px;
  padding: 1.5rem;
  border: 1px solid var(--brand-glass-border);
}

.troubleshoot h3 {
  color: var(--brand-gradient-start);
  margin-top: 1rem;
  font-size: 1.1rem;
}

.troubleshoot h3:first-child {
  margin-top: 0;
}

.troubleshoot ul {
  margin-left: 1.5rem;
  margin-bottom: 1.5rem;
}

.troubleshoot ul:last-child {
  margin-bottom: 0;
}

strong {
  color: var(--brand-text-primary);
  font-weight: 600;
}

code {
  background: var(--brand-bg-secondary);
  padding: 0.2rem 0.4rem;
  border-radius: 4px;
  font-family: 'Courier New', monospace;
  font-size: 0.9rem;
  color: var(--brand-gradient-start);
}
</style>