<template>
<div class="center-container">
  <h1>Importing a Portfolio</h1>
  <p>To import a previously exported portfolio, locate the "Import" button in the header section of the Portfolio view.</p>
  <img src="@/assets/images/docs/import-button.png" alt="Import Button" class="import-img" />
  <p>Click the "Import" button. A popup will appear prompting you to attach a CSV file.</p>
  <img src="@/assets/images/docs/import-popup.png" alt="Import Popup" class="import-img" />
  <p>The CSV file must be in the exact same format as the one generated by the export feature. Once attached, the system will correctly import the portfolio data, including all positions, transactions, and settings.</p>
</div>
</template>

<script setup lang="ts">
</script>

<style scoped lang="scss">
@use '@/style.scss' as *;

.center-container {
    display: flex;
    flex-direction: column;
    text-align: left;
    width: 100%;
    padding: 2rem 0;
}

.center-container h1 {
    font-size: 2.5rem;
    color: $text1;
    margin-bottom: 1.5rem;
    text-align: center;
}

.center-container p,
.center-container strong,
.center-container b {
    font-size: 1.4rem;
    color: $text2;
    margin-bottom: 1rem;
    line-height: 1.6;
    overflow-wrap: anywhere;
}

.center-container a {
    color: $accent2;
    text-decoration: underline;
    font-size: 1.4rem;
    overflow-wrap: anywhere;
}

.import-img {
    width: 100%;
    margin-bottom: 1rem;
}
</style>