/** Pino `redact` paths shared by every service's logger. */
export const REDACT_PATHS = [
    'password',
    'newPassword',
    'currentPassword',
    'passwordHash',
    'token',
    'accessToken',
    'refreshToken',
    'tempToken',
    'totpSecret',
    'recoveryCode',
    'recoveryCodes',
    'authorization',
    'cookie',
    'set-cookie',
    'req.headers.authorization',
    'req.headers.cookie',
    'res.headers["set-cookie"]',
    '*.password',
    '*.token',
    '*.totpSecret',
    'err.command.args',
];
