FROM node:20

WORKDIR /app

# Rest of your existing Dockerfile
COPY api ./api
COPY package.json ./package.json

RUN npm install

EXPOSE 5500

# Update start command to use SSL certificates
CMD ["node", "api/server.js"]